**Theoretical Questions:**

**Q.1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?**

**ANS:**
###Purpose and Advantages of NumPy in Scientific Computing and Data Analysis:

NumPy (Numerical Python) is a fundamental library for scientific computing and data analysis in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these data structures efficiently.

**How NumPy Enhances Python's Capabilities for Numerical Operations**

1.Efficient Handling of Large Datasets

NumPy arrays (ndarray) are more efficient than Python lists in terms of memory usage and speed. This is because NumPy uses contiguous memory storage and optimized C-based implementations.


2.Faster Computation

NumPy's operations are vectorized, meaning they apply operations to entire arrays instead of using Python loops, which significantly improves performance.

3.Rich Mathematical Functionality

Provides built-in functions for complex mathematical computations such as linear algebra, Fourier transforms, and statistical operations.

4.Broadcasting

Allows operations between arrays of different shapes without the need for explicit loops, making code more concise and efficient.

5.Interoperability with Other Libraries

NumPy integrates well with other scientific computing libraries such as SciPy, Pandas, Matplotlib, and scikit-learn.

6.Support for Multi-Dimensional Arrays and Matrix Operations

Unlike Python lists, NumPy provides efficient multi-dimensional array support, crucial for machine learning, deep learning, and image processing.

7.Memory Efficiency

NumPy arrays consume less memory compared to Python lists due to their fixed data types and optimized storage.

8.Random Number Generation

Provides an optimized random module for generating random numbers efficiently, useful in simulations and machine learning.

9.Ease of Use and Open-Source Nature

NumPy has a simple syntax and is widely used in the scientific community, making it an essential tool for researchers and data analysts.

**Conclusion**

NumPy enhances Python’s capabilities by providing efficient, high-speed numerical computations, reducing the need for loops, and enabling complex mathematical operations with ease. It serves as the foundation for many other data science and machine learning libraries.

**Q.2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?**

**ANS**:
###Comparison of np.mean() and np.average() in NumPy

Both np.mean() and np.average() are used to compute the average value of an array, but they have key differences in terms of functionality.

**Feature**
##np.mean()

**1.Basic Functionality**:Computes the arithmetic mean of an array.

**2.Weights Support**:No support for weights.

**3.Formula**:Mean=∑xi/N

**4.Default Behavior**:Computes mean along the specified axis (or the entire array if no axis is specified).

**5.Performance**:	Generally faster, as it performs simple division.

##np.average()

**1.BASIC FUNCTIONALITY**:Computes the weighted average of an array (can also behave like np.mean() if no weights are given).

**2.WEIGHT SUPPORT**:Supports weights via the weights parameter.

**3.FORMULA**:	Weighted Average=∑𝑤𝑖𝑥𝑖/∑𝑤𝑖(if weights are provided).

**4.DEFAULT BEHAVIOR**:Computes the weighted or simple average along the specified axis.

**5.PERFORMANCE**:Slightly slower when weights are used, as additional computations are required.

**When to Use np.mean() vs. np.average()**

**Use np.mean() When:**
You need a simple arithmetic mean without weights.

You want better performance for large datasets where weights are not required.

Example: Finding the average score of students in a class.

**Use np.average() When:**

You need to compute a weighted average, where some values have more importance than others.

Example: Calculating the final grade of a student where different assignments have different weightings.

**Conclusion**

Use np.mean() for a simple mean calculation.

Use np.average() when weighting is needed.

If no weights are provided, np.average() behaves like np.mean().

In [1]:
import numpy as np

data = np.array([10, 20, 30, 40])
mean_value = np.mean(data)
print(mean_value)  # Output: 25.0


25.0


In [2]:
data = np.array([10, 20, 30, 40])
weights = np.array([1, 2, 3, 4])  # Higher weight for later values
weighted_avg = np.average(data, weights=weights)
print(weighted_avg)  # Output: 30.0


30.0


**Q.3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.**

**ANS:** **Reversing a NumPy Array Along Different Axes**

NumPy provides several ways to reverse an array, depending on its dimensionality and the axis along which the reversal should occur.

1. Reversing a 1D NumPy Array

For a one-dimensional array, we can reverse the elements using slicing ([::-1]) or the np.flip() function.

2. Reversing a 2D NumPy Array

For a 2D array, reversal can be performed along different axes:

Conclusion:

Use slicing ([::-1]) for quick reversal in 1D arrays.

Use np.flip() for more explicit and flexible reversal in both 1D and 2D arrays.

Reverse rows with [::-1, :] or np.flip(arr, axis=0).

Reverse columns with [:, ::-1] or np.flip(arr, axis=1).

Reverse both rows and columns with np.flip(arr).

In [5]:
import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5])
reversed_arr = arr_1d[::-1]
print(reversed_arr)  # Output: [5 4 3 2 1]


[5 4 3 2 1]


In [2]:
reversed_arr = np.flip(arr_1d)
print(reversed_arr)  # Output: [5 4 3 2 1]


[5 4 3 2 1]


**Q.4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.**

**ANS:**
###Determining the Data Type of Elements in a NumPy Array In NumPy, the data type of elements in an array can be determined using the dtype attribute

Changing Data Type Explicitly (dtype Parameter)

When creating a NumPy array, you can specify the data type explicitly:

Checking Data Type of Each Element (arr.itemsize)

To check the number of bytes used by each element

Checking Data Type Using np.result_type()

If multiple arrays or scalars are involved in an operation:

Importance of Data Types in Memory Management and Performance

1. Memory Efficiency

NumPy arrays consume less memory compared to Python lists because they use fixed-size data types.

Choosing a smaller data type (e.g., int8 vs. int64) can save significant memory in large datasets.

2. Performance Optimization

Smaller data types lead to faster computations because they require fewer bytes to process.

Floating-point operations on float32 are generally faster than float64 due to reduced memory access time.

3. Avoiding Type Mismatch and Conversion Overhead

NumPy automatically upcasts data types when necessary, but this can cause unnecessary memory usage.

In [6]:
arr_int8 = np.array([1, 2, 3, 4], dtype=np.int8)
arr_int64 = np.array([1, 2, 3, 4], dtype=np.int64)

print(arr_int8.nbytes)  # Output: 4 bytes (1 byte per element)
print(arr_int64.nbytes)  # Output: 32 bytes (8 bytes per element)


4
32


In [7]:
arr_float32 = np.array([1.0, 2.0, 3.0], dtype=np.float32)
arr_float64 = np.array([1.0, 2.0, 3.0], dtype=np.float64)

print(arr_float32.nbytes, arr_float64.nbytes)  # Output: 12 bytes vs. 24 bytes


12 24


In [8]:
arr = np.array([1, 2, 3.5])  # Contains an integer and a float
print(arr.dtype)  # Output: float64 (to accommodate 3.5)


float64


**Q5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?**

**ANS:** Definition of ndarrays in NumPy

In NumPy, an ndarray (n-dimensional array) is a powerful multi-dimensional array object that provides fast and efficient operations on large datasets. It is the core data structure of NumPy and is represented by the numpy.ndarray class.

**Key Features of ndarrays**

1.Homogeneous Data: All elements in an ndarray must be of the same data type (e.g., integers, floats, or complex numbers), ensuring efficient memory usage.

2.Fixed Size: Unlike Python lists, the size of an ndarray is fixed once created and cannot be dynamically resized.

3.Multi-dimensional Support: NumPy arrays can have one or more dimensions (1D, 2D, 3D, etc.), making them ideal for handling matrices and tensors.

4.Efficient Memory Usage: NumPy arrays are stored in a contiguous block of memory, reducing overhead and enabling fast operations.

5.Vectorized Operations: NumPy supports element-wise operations, broadcasting, and advanced mathematical functions, making computations significantly faster than using loops with Python lists.

6.Support for Advanced Indexing & Slicing: NumPy allows slicing, boolean indexing, and fancy indexing, providing greater flexibility in data manipulation.

7.Integration with Other Libraries: Many scientific computing and machine learning libraries (e.g., SciPy, Pandas, TensorFlow) use NumPy arrays for data representation.
**Conclusion**

NumPy ndarray is a powerful alternative to Python lists, especially for numerical computations. It offers better performance, memory efficiency, and flexibility for handling large datasets and complex mathematical operations.

In [9]:
import numpy as np

# Creating a NumPy array
arr = np.array([1, 2, 3, 4, 5])
print(arr)  # Output: [1 2 3 4 5]

# Creating a Python list
lst = [1, 2, 3, 4, 5]
print(lst)  # Output: [1, 2, 3, 4, 5]


[1 2 3 4 5]
[1, 2, 3, 4, 5]


In [10]:
import time

# Large dataset
size = 10**6

# NumPy array performance
arr = np.arange(size)
start = time.time()
arr_sum = arr + 1  # Vectorized operation
end = time.time()
print("NumPy Time:", end - start)

# Python list performance
lst = list(range(size))
start = time.time()
lst_sum = [x + 1 for x in lst]  # Loop-based operation
end = time.time()
print("List Time:", end - start)


NumPy Time: 0.005908489227294922
List Time: 0.11254215240478516


**Q.6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.**

**ANS:**Performance Benefits of NumPy Arrays Over Python Lists

NumPy arrays (ndarrays) offer significant performance advantages over Python lists, especially for large-scale numerical computations. These benefits come from optimized memory storage, vectorized operations, and low-level implementation in C. Below, we analyze the key performance improvements:

1. Faster Execution Through Vectorized Operations

NumPy avoids explicit loops and uses vectorized operations, which are implemented in optimized C code.

Python lists require explicit loops, making operations slower.

2. Efficient Memory Usage

Python lists store references to objects, consuming more memory.

NumPy arrays use contiguous memory blocks with a single data type, reducing memory overhead.

3. Broadcasting: Avoiding Unnecessary Loops

NumPy broadcasting allows element-wise operations between arrays of different shapes without explicit loops.

Python lists require manual iteration or nested loops.

4. Optimized Low-Level Implementation

NumPy is implemented in C and Fortran, providing low-level optimizations.

Python lists rely on high-level dynamic typing, making them slower in computational tasks.

5. Parallel Processing and Multi-threading

NumPy operations utilize multi-threading and SIMD (Single Instruction Multiple Data) under the hood, while Python lists are limited by the Global Interpreter Lock (GIL).

**Conclusion**

NumPy arrays outperform Python lists in speed, memory efficiency, and ease of use for large-scale numerical operations. Key advantages include:


Less Memory Usage: NumPy arrays are more memory-efficient due to their contiguous storage and homogeneous data type.

Faster Execution: Vectorized operations eliminate Python loops, making computations significantly faster.

Broadcasting: Enables efficient computation without explicit iteration.

Optimized Built-in Functions: NumPy’s mathematical functions are written in C for high performance.

Parallel Processing: Uses multi-threading, unlike Python lists.

For scientific computing, machine learning, and data analysis, NumPy is the preferred choice over Python lists. 🚀

In [11]:
import numpy as np
import time

size = 10**6  # Large dataset

# NumPy array
arr = np.arange(size)
start = time.time()
arr_result = arr * 2  # Vectorized multiplication
end = time.time()
print("NumPy Time:", end - start)

# Python list
lst = list(range(size))
start = time.time()
lst_result = [x * 2 for x in lst]  # List comprehension (loop-based)
end = time.time()
print("List Time:", end - start)


NumPy Time: 0.009866714477539062
List Time: 0.09324407577514648


In [12]:
import sys

size = 1000000  # Large dataset

# NumPy array
arr = np.arange(size, dtype=np.int32)
print("NumPy Memory (bytes):", arr.nbytes)

# Python list
lst = list(range(size))
print("Python List Memory (bytes):", sys.getsizeof(lst) + sum(sys.getsizeof(x) for x in lst))


NumPy Memory (bytes): 4000000
Python List Memory (bytes): 36000056


In [13]:
arr = np.array([1, 2, 3, 4, 5])
print(arr + 10)  # NumPy automatically broadcasts

# Python list (manual loop required)
lst = [1, 2, 3, 4, 5]
print([x + 10 for x in lst])  # Slower and less efficient


[11 12 13 14 15]
[11, 12, 13, 14, 15]


In [14]:
size = 1000000

# NumPy dot product
arr1 = np.random.rand(size)
arr2 = np.random.rand(size)
start = time.time()
dot_product = np.dot(arr1, arr2)  # Optimized C implementation
end = time.time()
print("NumPy Dot Product Time:", end - start)

# Python list dot product
lst1 = list(np.random.rand(size))
lst2 = list(np.random.rand(size))
start = time.time()
dot_product_list = sum(x * y for x, y in zip(lst1, lst2))  # Manual loop
end = time.time()
print("Python List Dot Product Time:", end - start)


NumPy Dot Product Time: 0.0018596649169921875
Python List Dot Product Time: 0.21775078773498535


In [15]:
arr = np.random.rand(1000000)
%timeit arr + arr  # Uses parallel execution internally


1.21 ms ± 138 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


**Q.7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output**

**ANS:**Comparison of vstack() and hstack() in NumPy

In NumPy, the functions vstack() (vertical stacking) and hstack() (horizontal stacking) are used to combine multiple arrays along different axes.

**Function**
###np.vstack()

Stacks Along:	Vertical (Row-wise) → Axis 0

Dimension Increased:Adds new rows

Behavior: Stacks arrays on top of each other

###np.hstack()

Stacks Along:	horizontal  (column -wise) → Axis 1

Dimension Increased:Adds new column

Behavior: Stacks arrays side by side.

1. vstack() – Vertical Stacking

Combines arrays row-wise (along axis=0).

The number of columns in all arrays must be the same.

2. hstack() – Horizontal Stacking

Combines arrays column-wise (along axis=1).

The number of rows in all arrays must be the same.

Conclusion

Use vstack() when stacking arrays vertically (row-wise).

Use hstack() when stacking arrays horizontally (column-wise).

Ensure that the arrays have matching dimensions in the appropriate direction before stacking.


In [16]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

result_vstack = np.vstack((arr1, arr2))
print(result_vstack)


[[1 2]
 [3 4]
 [5 6]]


In [17]:
arr3 = np.array([[7], [8]])

result_hstack = np.hstack((arr1, arr3))
print(result_hstack)


[[1 2 7]
 [3 4 8]]


**Q.8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions**

**ANS:**1. fliplr() – Flip Left to Right (Horizontally)

Reverses the order of columns, keeping the rows unchanged.

Requires a 2D array or higher; does not work on 1D arrays.

2. flipud() – Flip Up to Down (Vertically)

Reverses the order of rows, keeping the columns unchanged.

Works for both 1D and 2D arrays.

Conclusion

Use fliplr() when you want to reverse the order of columns (flip left to right).

Use flipud() when you want to reverse the order of rows (flip top to bottom).

flipud() can be applied to 1D and 2D arrays, while fliplr() requires at least a 2D array.

In [18]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

result_fliplr = np.fliplr(arr)
print(result_fliplr)


[[3 2 1]
 [6 5 4]]


In [19]:
result_flipud = np.flipud(arr)
print(result_flipud)


[[4 5 6]
 [1 2 3]]


 **Q.9. Discuss the functionality of the array_split() method in NumPy. How
does it handle uneven splits?**

**ANS:** Understanding array_split() in NumPy

The array_split() method in NumPy is used to split an array into multiple sub-arrays. It is similar to split(), but it can handle cases where the array cannot be evenly divided.

**Key Features of array_split()**

1.Splits an array into specified parts: It divides an array into a given number of sub-arrays.

2.Handles Uneven Splits: If the array size is not evenly divisible, array_split() distributes the extra elements evenly among the first few splits.

3.Supports Multiple Axes: You can specify which axis to split along using the axis parameter.

**How array_split() Handles Uneven Splits**

.If the array length is not evenly divisible by the number of splits, some sub-arrays will have extra elements.

.The first few sub-arrays receive the extra elements to maintain the closest even distribution.

**Conclusion**

array_split() splits arrays into sub-arrays, handling both even and uneven splits.

If the array cannot be divided evenly, extra elements are distributed to the first few sub-arrays.

It supports splitting along different axes, making it useful for multi-dimensional arrays.


In [20]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
result = np.array_split(arr, 3)  # Splitting into 3 equal parts

for subarray in result:
    print(subarray)


[1 2]
[3 4]
[5 6]


**Q.10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?**

**ANS:** **Vectorization and Broadcasting in NumPy: Concepts & Efficiency**

NumPy provides vectorization and broadcasting, two powerful features that enable fast and memory-efficient array operations. These concepts help eliminate explicit Python loops, leveraging highly optimized C and Fortran implementations.

1. Vectorization: Fast Element-wise Operations

Definition:
Vectorization refers to the ability to perform element-wise operations on entire arrays without using explicit loops. It transforms operations that would typically require loops in Python into efficient, low-level operations executed in compiled C code.

Benefits:

✅ Faster Execution: Eliminates Python loops, utilizing optimized NumPy functions.

✅ Concise Code: More readable and easier to maintain.

✅ Memory Efficient: Reduces overhead by leveraging CPU cache and SIMD (Single Instruction Multiple Data).

2. Broadcasting: Handling Operations on Different-Shaped Arrays

Definition:

Broadcasting allows NumPy to perform operations on arrays of different shapes by expanding the smaller array’s dimensions without making actual copies. This avoids memory-intensive operations and makes calculations more efficient.

Rules of Broadcasting:

If the dimensions match exactly, NumPy performs element-wise operations.

If the dimensions differ, NumPy automatically expands the smaller array’s shape to match the larger one.

If a dimension has size 1, it is stretched to match the other array’s shape.

If dimensions are incompatible, NumPy raises an error.

**Conclusion:**

✅ Vectorization speeds up numerical computations by removing explicit loops.

✅ Broadcasting allows efficient operations on different-shaped arrays without memory overhead.

✅ Together, they enable highly optimized computations, making NumPy ideal for scientific computing and machine learning.

In [21]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[10],  # Shape: (2,1)
                 [20]])

result = arr1 + arr2  # Broadcasting arr2 across columns
print(result)


[[11 12 13]
 [24 25 26]]


**Practical Questions:**

**Q.1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns**

In [22]:
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
arr = np.random.randint(1, 101, (3, 3))

print("Original Array:")
print(arr)

# Interchange rows and columns using transpose
transposed_arr = arr.T  # OR use np.transpose(arr)

print("\nTransposed Array:")
print(transposed_arr)


Original Array:
[[16 58 18]
 [65 76 60]
 [34 63 75]]

Transposed Array:
[[16 65 34]
 [58 76 63]
 [18 60 75]]


**Q.2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.**

In [23]:
import numpy as np

# Step 1: Create a 1D array with 10 elements
arr = np.arange(1, 11)  # Generates numbers from 1 to 10

print("Original 1D Array:")
print(arr)

# Step 2: Reshape into a 2x5 array
arr_2x5 = arr.reshape(2, 5)
print("\nReshaped to 2x5 Array:")
print(arr_2x5)

# Step 3: Reshape into a 5x2 array
arr_5x2 = arr.reshape(5, 2)
print("\nReshaped to 5x2 Array:")
print(arr_5x2)


Original 1D Array:
[ 1  2  3  4  5  6  7  8  9 10]

Reshaped to 2x5 Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Reshaped to 5x2 Array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


**Q.3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.**

In [24]:
import numpy as np

# Step 1: Create a 4x4 array with random float values
arr = np.random.rand(4, 4)  # Random values between 0 and 1

print("Original 4x4 Array:")
print(arr)

# Step 2: Add a border of zeros using np.pad()
arr_padded = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

print("\n6x6 Array with Zero Border:")
print(arr_padded)


Original 4x4 Array:
[[0.38557457 0.1705932  0.19478774 0.66806136]
 [0.36544939 0.88858365 0.62074906 0.3004847 ]
 [0.14285798 0.7366616  0.49392138 0.98847756]
 [0.80432716 0.29655593 0.95427958 0.60472737]]

6x6 Array with Zero Border:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.38557457 0.1705932  0.19478774 0.66806136 0.        ]
 [0.         0.36544939 0.88858365 0.62074906 0.3004847  0.        ]
 [0.         0.14285798 0.7366616  0.49392138 0.98847756 0.        ]
 [0.         0.80432716 0.29655593 0.95427958 0.60472737 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


**Q.4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.**

In [33]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
arr = np.arange(10, 61, 5)

print("Array of integers from 10 to 60 with step of 5:")
print(arr)


Array of integers from 10 to 60 with step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


**Q.5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.**

In [32]:
import numpy as np

# Create a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations using np.vectorize

# Uppercase transformation
uppercase_arr = np.vectorize(str.upper)(arr)

# Lowercase transformation
lowercase_arr = np.vectorize(str.lower)(arr)

# Title case transformation
titlecase_arr = np.vectorize(str.title)(arr)

# Capitalize transformation
capitalize_arr = np.vectorize(str.capitalize)(arr)

# Display the results
print("Original Array:")
print(arr)

print("\nUppercase:")
print(uppercase_arr)

print("\nLowercase:")
print(lowercase_arr)

print("\nTitle Case:")
print(titlecase_arr)

print("\nCapitalize:")
print(capitalize_arr)


Original Array:
['python' 'numpy' 'pandas']

Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
['python' 'numpy' 'pandas']

Title Case:
['Python' 'Numpy' 'Pandas']

Capitalize:
['Python' 'Numpy' 'Pandas']


**Q.6. Generate a NumPy array of words. Insert a space between each character of every word in the array.**

In [31]:
import numpy as np

# Generate a NumPy array of words
words = np.array(['hello', 'world', 'numpy', 'array'])

# Function to insert spaces between characters of a word
def insert_spaces(word):
    return ' '.join(word)

# Apply the function to each word in the array using np.vectorize
vectorized_insert_spaces = np.vectorize(insert_spaces)
words_with_spaces = vectorized_insert_spaces(words)

print("Original Words:")
print(words)

print("\nWords with Spaces Between Characters:")
print(words_with_spaces)


Original Words:
['hello' 'world' 'numpy' 'array']

Words with Spaces Between Characters:
['h e l l o' 'w o r l d' 'n u m p y' 'a r r a y']


**Q.7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.**

In [30]:
import numpy as np

# Create two 2D NumPy arrays
arr1 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Array 1:")
print(arr1)

print("\nArray 2:")
print(arr2)

# Element-wise addition
addition_result = arr1 + arr2
print("\nElement-wise Addition:")
print(addition_result)

# Element-wise subtraction
subtraction_result = arr1 - arr2
print("\nElement-wise Subtraction:")
print(subtraction_result)

# Element-wise multiplication
multiplication_result = arr1 * arr2
print("\nElement-wise Multiplication:")
print(multiplication_result)

# Element-wise division
division_result = arr1 / arr2
print("\nElement-wise Division:")
print(division_result)


Array 1:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Array 2:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Element-wise Addition:
[[11 22 33]
 [44 55 66]
 [77 88 99]]

Element-wise Subtraction:
[[ 9 18 27]
 [36 45 54]
 [63 72 81]]

Element-wise Multiplication:
[[ 10  40  90]
 [160 250 360]
 [490 640 810]]

Element-wise Division:
[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]


**Q.8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.**

In [29]:
import numpy as np

# Step 1: Create a 5x5 identity matrix
identity_matrix = np.eye(5)

print("5x5 Identity Matrix:")
print(identity_matrix)

# Step 2: Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)

print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


**Q.9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array**

In [28]:
import numpy as np

# Function to check if a number is prime
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):  # Check divisibility up to sqrt(n)
        if n % i == 0:
            return False
    return True

# Generate an array of 100 random integers between 0 and 1000
np.random.seed(42)  # For reproducibility
rand_arr = np.random.randint(0, 1001, 100)

# Find prime numbers in the array
prime_numbers = np.array([num for num in rand_arr if is_prime(num)])

# Display results
print("Original Array:")
print(rand_arr)

print("\nPrime Numbers in the Array:")
print(prime_numbers)


Original Array:
[102 435 860 270 106  71 700  20 614 121 466 214 330 458  87 372  99 871
 663 130 661 308 769 343 491 413 805 385 191 955 276 160 459 313  21 252
 747 856 560 474  58 510 681 475 699 975 782 189 957 686 957 562 875 566
 243 831 504 130 484 818 646  20 840 166 273 387 600 315  13 241 776 345
 564 897 339  91 366 955 454 427 508 775 942  34 205  80 931 561 871 387
   1 389 565 105 771 821 476 702 401 729]

Prime Numbers in the Array:
[ 71 661 769 491 191 313  13 241 389 821 401]


**Q.10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.**

In [27]:
import numpy as np

# Generate a NumPy array representing daily temperatures for 30 days (random values between 20°C and 35°C)
np.random.seed(42)  # For reproducibility
daily_temps = np.random.uniform(20, 35, 30)  # 30 random temperatures

print("Daily Temperatures (°C):")
print(daily_temps)

# Reshape the first 28 days into 4 weeks of 7 days
weeks = daily_temps[:28].reshape(4, 7)

# Compute weekly averages
weekly_avg = np.mean(weeks, axis=1)

# Handling the remaining 2 days separately
remaining_avg = np.mean(daily_temps[28:])  # Average of last 2 days

# Display results
print("\nWeekly Averages (°C):")
for i, avg in enumerate(weekly_avg, 1):
    print(f"Week {i}: {avg:.2f}°C")

print(f"\nRemaining 2 days Average: {remaining_avg:.2f}°C")


Daily Temperatures (°C):
[25.61810178 34.2607146  30.97990913 28.97987726 22.34027961 22.33991781
 20.87125418 32.99264219 29.01672518 30.62108867 20.30876741 34.54864778
 32.48663961 23.18508666 22.72737451 22.75106765 24.56363364 27.87134647
 26.47917528 24.3684371  29.17779342 22.09240791 24.38216973 25.49542765
 26.84104976 31.77763942 22.99510673 27.71351658 28.88621853 20.69675619]

Weekly Averages (°C):
Week 1: 26.48°C
Week 2: 29.02°C
Week 3: 25.42°C
Week 4: 25.90°C

Remaining 2 days Average: 24.79°C
